repos:
-   repo: "https://github.com/matthewhughes934/pre-commit-format-markdown"
    rev: v0.5.0
    hooks:
    -   id: format-markdown-docker
        exclude: "tests/.*.md"
-   repo: https://gitlab.com/matthewhughes/common-changelog
    rev: v0.2.0
    hooks:
    -   id: validate-changelog
