repos:
-   repo: "https://github.com/matthewhughes934/pre-commit-format-markdown"
    rev: v0.3.0
    hooks:
    -   id: format-markdown-docker
        exclude: "tests/.*.md"
        args: ["--width", "80"]
