name: tests
on: push

env:
  TAG: cmark-image

jobs:
  name: test-script
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          push: false
          tags: ${{ env.TAG }}
      - name: Test
        run: >
          docker run 
          --rm 
          --volume ${{ github.workspace }}/:/workdir
          ${{ env.TAG }}
          /workdir/tests/test.sh

